apiVersion: v1
kind: ClusterRole
metadata:
  name: secret-provisioner
rules:
- apiGroups: null
  attributeRestrictions: null
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
