apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: compile-artifact
  name: compile-artifact
spec:
  output:
    to:
      kind: ImageStreamTag
      name: compile-artifact:latest
  source:
    contextDir: builds/chained-builds/compile-artifact
    git:
      uri: https://github.com/leandroberetta/openshift-recipes.git
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: maven:latest
    type: Docker