apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: app
  name: app
spec:
  output:
    to:
      kind: ImageStreamTag
      name: app:latest
  source:
    contextDir: builds/chained-builds/app
    git:
      uri: https://github.com/leandroberetta/openshift-recipes.git
    type: Git
    images:
    - from: 
        kind: ImageStreamTag
        name: compile-artifact:latest
      paths: 
      - sourcePath: /app/target/openshift-hello-world-thorntail.jar
        destinationDir: "."
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: java:openjdk-8-alpine
    type: Docker